services:
  - type: web
    name: zlang
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/zlang --web
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: RUST_LOG
        value: info